---
title: "Lists - In Class Exercises"
author: "Adam N"
date: "DATA 2401"
output: html_document
---

# Exercises: 

Make a list that contains the information on a single playing card. Suit, face, and value. 

```{r}
card <- list(
  suit = "Hearts",
  face = "King",
  value = 10
)

card_option <- list(
    suit = c("Heart","diamond","")
)

```


Make a second list where each element contains all the options for suit, face, and value, respectively. 

```{r}
options <- list(
  suits = c("Hearts", "Diamonds", "Clubs", "Spades"),
  faces = c("Ace", "1", "2", "3", "4", "5", "6", "7", "8", "9", "Jack", "Queen", "King"),
  values = c(Ace = 11, "2" = 2, "3" = 3, "4" = 4, "5" = 5, "6" = 6, "7" = 7, "8" = 8, "9" = 9, "10" = 10, Jack = 10, Queen = 10, King = 10)
)

print(options)


```


If `Newlist <- list(a=1:10, b="Good morning", c="Hi")`, write an R statement that will add 1 to each element of the first vector in Newlist.

```{r}
Newlist <- list(a=1:10, b="Good morning", c="Hi")
Newlist$a <- Newlist$a + 1


print(Newlist)


```

If `b <- list(a=1:10, c="Hello", d="AA")`, write an R expression that will give all elements of the first vector of b, except the second, and write another that returns only elements of `a` that are greater than 7.

```{r}
b <- list(a=1:10, c="Hello", d="AA")
b$a[-2]
b$a[c(1,3:length(b$a))]

b$a[b$a > 7]

```

Let `x <- list(a=5:10, c="Hello", d="AA")`, write an R statement to add a new item z = "NewItem" to the list x.

```{r}
x <- list(a=5:10, c="Hello", d="AA")
x $z <- "NewItem"
print(x)


```


